### PR TITLE
lat/lon

### PR DESCRIPTION
**Pull request by magnusmanske**

### CODE REVIEW

**Comment by puethe** [comment]
Yes, min/max validation would be good. Other than that there's some problem in the test, as it's comparing float values with "=". This might just fail randomly. There should be some function like "floatequal" in the Python math library. Please use that or sth equivalent.

**Comment by puethe** [comment]
Validation of lat/lon is especially important because of the different definitions people might use. Does longitude stretch from -180 to +180, or from 0 to 360? Need to settle on one of them.

**Comment by garethpeat** [comment]
Good point about the tests, @puethe. There's also a `DecimalField` which maps to python's `Decimal` type. This would help with equality checks, but is unlikely to have database support in SQLite3. If we stick with `FloatField`, then try using [unittest.TestCase.assertAlmostEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual).

`DecimalField` is commonly used for currency, [it seems](https://stackoverflow.com/questions/2569015/django-floatfield-or-decimalfield-for-currency).

**Comment by puethe** [comment]
Ah didn't know this unittest function. That seems like the perfect thing to use.

**Pull request merged**
